# Generated by Django 4.1.7 on 2023-02-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='singer',
            options={'verbose_name': 'исполнитель', 'verbose_name_plural': 'исполнители'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.PositiveIntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
