# Generated by Django 4.1.7 on 2023-02-25 13:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_album_options_alter_singer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='albums',
        ),
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.PositiveIntegerField(validators=[api.models.validator_year], verbose_name='Год выпуска'),
        ),
    ]
